# Generated by Django 4.1.3 on 2022-12-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=30)),
                ('band_description', models.TextField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='buddyguild_admins_set', to='account.buddyprofile')),
                ('list_of_owned_games', models.ManyToManyField(blank=True, to='game.game')),
                ('members', models.ManyToManyField(blank=True, related_name='buddyguild_members_set', to='account.buddyprofile')),
            ],
        ),
    ]
