# Generated by Django 4.1.3 on 2022-12-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buddyguild',
            old_name='band_name',
            new_name='guild_name',
        ),
        migrations.AddField(
            model_name='buddyguild',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
