# Generated by Django 4.1.3 on 2022-12-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_rename_band_name_buddyguild_guild_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyguild',
            name='guild_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
