# Generated by Django 4.1.3 on 2022-12-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0003_alter_buddyguild_guild_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buddyguild',
            old_name='band_description',
            new_name='guild_description',
        ),
    ]
