# Generated by Django 4.1.3 on 2022-12-04 14:42

import BoardGameBuddy.guild.cust_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0004_rename_band_description_buddyguild_guild_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyguild',
            name='guild_picture',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles/guild_photo/', validators=[BoardGameBuddy.guild.cust_validators.validate_file_size]),
        ),
    ]
