# Generated by Django 4.1.3 on 2022-12-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('guild', '0005_buddyguild_guild_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddyguild',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='buddyguild',
            name='members',
        ),
        migrations.AddField(
            model_name='buddyguild',
            name='admins',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='buddyguild_admins_set', to='account.buddyprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buddyguild',
            name='members',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='buddyguild_members_set', to='account.buddyprofile'),
            preserve_default=False,
        ),
    ]
