# Generated by Django 4.1.3 on 2022-12-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('guild', '0006_remove_buddyguild_admins_remove_buddyguild_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyguild',
            name='admins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buddyguild_admins_set', to='account.buddyprofile'),
        ),
        migrations.AlterField(
            model_name='buddyguild',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buddyguild_members_set', to='account.buddyprofile'),
        ),
    ]
