# Generated by Django 4.1.3 on 2022-12-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('guild', '0007_alter_buddyguild_admins_alter_buddyguild_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddyguild',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='buddyguild',
            name='members',
        ),
        migrations.AddField(
            model_name='buddyguild',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='buddyguild_admins_set', to='account.buddyprofile'),
        ),
        migrations.AddField(
            model_name='buddyguild',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='buddyguild_members_set', to='account.buddyprofile'),
        ),
    ]
