# Generated by Django 4.1.3 on 2022-12-11 18:45

import BoardGameBuddy.guild.cust_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0009_alter_buddyguild_admins_alter_buddyguild_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyguild',
            name='guild_picture',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles/guild_photos/', validators=[BoardGameBuddy.guild.cust_validators.validate_file_size]),
        ),
    ]
