# Generated by Django 4.1.3 on 2022-12-17 20:06

import BoardGameBuddy.guild.cust_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0010_alter_buddyguild_guild_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buddyguild',
            options={'ordering': ['guild_name']},
        ),
        migrations.AlterField(
            model_name='buddyguild',
            name='guild_picture',
            field=models.ImageField(blank=True, null=True, upload_to='guild_photos', validators=[BoardGameBuddy.guild.cust_validators.validate_file_size]),
        ),
    ]
