# Generated by Django 4.1.3 on 2022-12-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='band',
            new_name='guild',
        ),
    ]
