# Generated by Django 4.1.3 on 2022-12-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('guild', '0009_alter_buddyguild_admins_alter_buddyguild_members'),
        ('common', '0003_delete_gamecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestJoiningGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('from_buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.buddyprofile')),
                ('to_guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild.buddyguild')),
            ],
        ),
    ]
