# Generated by Django 4.1.3 on 2022-12-11 17:55

import BoardGameBuddy.account.cust_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos', validators=[BoardGameBuddy.account.cust_validators.validate_file_size]),
        ),
    ]
