# Generated by Django 4.1.3 on 2022-12-04 13:19

import BoardGameBuddy.game.cust_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2), BoardGameBuddy.game.cust_validators.validate_first_capital_letter_of_title, BoardGameBuddy.game.cust_validators.validate_title_chars])),
                ('description', models.TextField(max_length=300)),
                ('genre', models.CharField(choices=[('Adventure', 'Adventure'), ('Competitive', 'Competitive'), ('Cooperative', 'Cooperative'), ('Card Game', 'Card Game'), ('Dice', 'Dice'), ('Educational', 'Educational'), ('Fantasy', 'Fantasy'), ('Mythology', 'Mythology'), ('Party Game', 'Party Game'), ('Racing', 'Racing'), ('Science Fiction', 'Science Fiction'), ('War Game', 'War Game')], max_length=20)),
                ('release_year', models.IntegerField(validators=[BoardGameBuddy.game.cust_validators.YearRangeValidator(1980, 2022, 'Year must be between 1980 and 2022.')])),
                ('max_players', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('complexity', models.CharField(choices=[('light', 'light'), ('moderate', 'moderate'), ('complex', 'complex'), ('very complex', 'very complex')], max_length=15)),
                ('publisher', models.CharField(max_length=30, validators=[BoardGameBuddy.game.cust_validators.validate_publisher_chars])),
                ('photo_url', models.URLField()),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
    ]
