# Generated by Django 4.1.3 on 2022-12-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Competitive', 'Competitive'), ('Cooperative', 'Cooperative'), ('Card Game', 'Card Game'), ('Dice', 'Dice'), ('Educational', 'Educational'), ('Economy', 'Economy'), ('Fantasy', 'Fantasy'), ('Mythology', 'Mythology'), ('Management', 'Management'), ('Party Game', 'Party Game'), ('Racing', 'Racing'), ('Science Fiction', 'Science Fiction'), ('War Game', 'War Game')], max_length=20),
        ),
    ]
