# Generated by Django 4.1.3 on 2022-12-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title']},
        ),
    ]
